import { RoomDefinition } from '../types';
import { Room1 } from './Room1';
import { Room2 } from './Room2';
import { Room3 } from './Room3';
import { Room4 } from './Room4';
import { Room5 } from './Room5';
import { Room6 } from './Room6';
import { Room7 } from './Room7';
import { Room8 } from './Room8';
import { Room9 } from './Room9';
import { Room10 } from './Room10';
import { Room11 } from './Room11';
import { Room12 } from './Room12';
import { Room13 } from './Room13';
import { Room14 } from './Room14';
import { Room15 } from './Room15';
import { Room16 } from './Room16';
import { Room17 } from './Room17';
import { Room18 } from './Room18';
import { Room19 } from './Room19';
import { Room20 } from './Room20';

export const ROOMS: RoomDefinition[] = [
  {
    id: 1,
    chapter: 1,
    chapterTitle: 'The Awakening',
    title: 'Room 01',
    instruction: 'Press the red button.',
    defaultSuccessMessage: 'Nice.',
    defaultSuccessSubmessage: 'That was suspiciously easy.',
    defaultTrollTitle: 'Really?',
    defaultTrollMessage: 'You had one job: press the red button.',
    hint: 'Literally just press the big red button. It is Room 1.',
    component: Room1,
  },
  {
    id: 2,
    chapter: 1,
    chapterTitle: 'The Awakening',
    title: 'Room 02',
    instruction: 'Press the red button twice.',
    defaultSuccessMessage: 'Nice Math.',
    defaultSuccessSubmessage: '1 + 1 = Success. Look at you following instructions.',
    defaultTrollTitle: 'Count Again',
    defaultTrollMessage: 'The button requires two presses.',
    hint: 'Press the red button two times in total.',
    component: Room2,
  },
  {
    id: 3,
    chapter: 1,
    chapterTitle: 'The Awakening',
    title: 'Room 03',
    instruction: 'Press the red button.',
    defaultSuccessMessage: 'Good Choice.',
    defaultSuccessSubmessage: 'You actually listened this time.',
    defaultTrollTitle: 'Wrong Choice.',
    defaultTrollMessage: 'I said RED.',
    hint: 'There are two buttons. Only press the red one!',
    component: Room3,
  },
  {
    id: 4,
    chapter: 1,
    chapterTitle: 'The Awakening',
    title: 'Room 04',
    instruction: 'Press the button.',
    defaultSuccessMessage: 'Gotcha!',
    defaultSuccessSubmessage: 'Cardio is important for buttons too.',
    defaultTrollTitle: 'Too Slow!',
    defaultTrollMessage: 'Keep chasing it until it runs out of breath.',
    hint: 'Keep trying to click the button. It will get tired after a few attempts!',
    component: Room4,
  },
  {
    id: 5,
    chapter: 1,
    chapterTitle: 'The Awakening',
    title: 'Room 05',
    instruction: 'Press the button.',
    defaultSuccessMessage: 'Invisible Victory.',
    defaultSuccessSubmessage: 'Object permanence is a marvelous human trait.',
    defaultTrollTitle: 'Vanished!',
    defaultTrollMessage: 'Where did it go?',
    hint: 'When the button disappears, look around the chamber walls for the relocated ghost node.',
    component: Room5,
  },
  {
    id: 6,
    chapter: 2,
    chapterTitle: 'Question Everything',
    title: 'Room 06',
    instruction: 'PRESS THE RED BUTTON.',
    defaultSuccessMessage: "Good. You're learning.",
    defaultSuccessSubmessage: 'Questioning authority is a feature, not a bug.',
    defaultTrollTitle: 'You really trust the instructions?',
    defaultTrollMessage: 'Rule #1 of ELZZUP: Instructions are not your friends.',
    hint: 'Maybe the instruction is lying to you this time.',
    component: Room6,
  },
  {
    id: 7,
    chapter: 2,
    chapterTitle: 'Question Everything',
    title: 'Room 07',
    instruction: 'Press the correct button.',
    defaultSuccessMessage: 'You actually looked around.',
    defaultSuccessSubmessage: 'Observation beats impulsive clicking every single time.',
    defaultTrollTitle: 'Wrong Button.',
    defaultTrollMessage: 'Look around the chamber for subtle clues.',
    hint: 'Check the diagnostic logs in the top corner of the chamber.',
    component: Room7,
  },
  {
    id: 8,
    chapter: 2,
    chapterTitle: 'Question Everything',
    title: 'Room 08',
    instruction: 'FOLLOW THE INSTRUCTIONS.',
    defaultSuccessMessage: "Maybe don't trust me.",
    defaultSuccessSubmessage: 'The instructions are written by someone who wants to trap you.',
    defaultTrollTitle: 'The instruction is the trap.',
    defaultTrollMessage: 'You believed the command word for word. Have you learned nothing from ELZZUP?',
    hint: 'Look closely at what changes or is bypassed when you ignore the main command.',
    component: Room8,
  },
  {
    id: 9,
    chapter: 2,
    chapterTitle: 'Question Everything',
    title: 'Room 09',
    instruction: 'INITIALIZE DEFEAT PROTOCOL.',
    defaultSuccessMessage: 'You saw through the illusion.',
    defaultSuccessSubmessage: "Room 9 wasn't the end. Now enter the true final trial.",
    defaultTrollTitle: 'Did you really think that was it?',
    defaultTrollMessage: "Room 9 is not the end. Look closely at your 'victory'.",
    hint: 'Inspect the victory screen carefully for inconsistencies or room counters.',
    component: Room9,
  },
  {
    id: 10,
    chapter: 2,
    chapterTitle: 'Question Everything',
    title: 'Room 10',
    instruction: 'DO EXACTLY WHAT I SAY.',
    defaultSuccessMessage: 'Okay.',
    defaultSuccessSubmessage: 'You win. ELZZUP defeated.',
    defaultTrollTitle: 'The archives do not lie.',
    defaultTrollMessage: 'Remember what you did in previous chambers.',
    hint: 'Invert false commands, harmonize breaker frequencies, and spell the unmasked secret backwards.',
    component: Room10,
  },
  {
    id: 11,
    chapter: 3,
    chapterTitle: 'The Deep Core',
    title: 'Room 11',
    instruction: 'PRESS BUTTONS IN NUMERICAL ORDER.',
    defaultSuccessMessage: 'Register Inverted.',
    defaultSuccessSubmessage: 'Counting backwards: the first altered rule.',
    defaultTrollTitle: 'Counter Inverted',
    defaultTrollMessage: 'Did you really think counting forward works in a corrupted system?',
    hint: 'Check the top diagnostic log: the stack decrements from 4 down to 1.',
    component: Room11,
  },
  {
    id: 12,
    chapter: 3,
    chapterTitle: 'The Deep Core',
    title: 'Room 12',
    instruction: 'DISARM THE VOLATILE CIRCUIT.',
    defaultSuccessMessage: 'Circuit Disarmed.',
    defaultSuccessSubmessage: 'You checked the schematic instead of falling for the red wire bait.',
    defaultTrollTitle: 'Obvious Trap',
    defaultTrollMessage: 'You cut the giant flashing red wire without reading the schematic.',
    hint: 'Read the schematic note in the corner: Blue wire is the grounded disarm relay.',
    component: Room12,
  },
  {
    id: 13,
    chapter: 3,
    chapterTitle: 'The Deep Core',
    title: 'Room 13',
    instruction: 'PRESS THE GREEN BUTTON TO CONFIRM.',
    defaultSuccessMessage: 'True Spectrum Unlocked.',
    defaultSuccessSubmessage: 'Objects are not always what they appear under deceptive lighting.',
    defaultTrollTitle: 'Chromatically Deceived',
    defaultTrollMessage: 'That button only looked green under the faulty ambient light.',
    hint: 'Toggle the True Spectrum Optical Filter to reveal the authentic green emitter.',
    component: Room13,
  },
  {
    id: 14,
    chapter: 3,
    chapterTitle: 'The Deep Core',
    title: 'Room 14',
    instruction: 'CALIBRATE THE ROTARY DIALS.',
    defaultSuccessMessage: 'Overload Neutralized.',
    defaultSuccessSubmessage: 'You adapted when the system shifted the rules mid-attempt.',
    defaultTrollTitle: 'Equilibrium Failed',
    defaultTrollMessage: 'The sum of Dial A and Dial B must equal exactly 100%.',
    hint: 'Set Dial A to 50% and Dial B to 50% (or any split summing to 100%) and stabilize.',
    component: Room14,
  },
  {
    id: 15,
    chapter: 3,
    chapterTitle: 'The Deep Core',
    title: 'Room 15',
    instruction: 'AUTHORIZE SECURITY OVERRIDE.',
    defaultSuccessMessage: 'Interference Outsmarted.',
    defaultSuccessSubmessage: 'You bypassed ELZZUP’s disruptions by latching the override.',
    defaultTrollTitle: 'Interference Overload',
    defaultTrollMessage: 'ELZZUP reset the unsecured relays. Engage the override lock.',
    hint: 'Activate all 3 switches and immediately engage the override latch before ELZZUP resets them.',
    component: Room15,
  },
  {
    id: 16,
    chapter: 4,
    chapterTitle: 'The Glitched Abyss',
    title: 'Room 16',
    instruction: 'EXECUTE DUAL-TIER BYPASS.',
    defaultSuccessMessage: 'Multi-Stage Bypass Complete.',
    defaultSuccessSubmessage: 'Key captured and harmonic parity synchronized in reverse.',
    defaultTrollTitle: 'Harmonic Frequency Mismatch',
    defaultTrollMessage: 'Breaker parity requires highest frequency first (Gamma → Beta → Alpha).',
    hint: 'Catch the wandering bypass key, then tune breakers from highest to lowest frequency.',
    component: Room16,
  },
  {
    id: 17,
    chapter: 4,
    chapterTitle: 'The Glitched Abyss',
    title: 'Room 17',
    instruction: 'SOLVE 3 STAGES: NOTICE, QUESTION, & DEDUCE.',
    defaultSuccessMessage: 'Chamber 17 Overridden.',
    defaultSuccessSubmessage: 'You noticed the true conductors, questioned the misleading jargon, and deduced the harmonic key.',
    defaultTrollTitle: 'Deduction Fault',
    defaultTrollMessage: 'Notice everyday conductors over fancy labels, question thermal traps, and deduce the chamber key.',
    hint: 'Stage 1: Metal paperclip. Stage 2: Copper heatsink. Stage 3: Dial A=1, Dial B=1, Dial C=7.',
    component: Room17,
  },
  {
    id: 18,
    chapter: 4,
    chapterTitle: 'The Glitched Abyss',
    title: 'Room 18',
    instruction: 'SOLVE 3 STAGES: DISCOVER THE RULE, APPLY, & COMBINE.',
    defaultSuccessMessage: 'Gate 18 Overridden.',
    defaultSuccessSubmessage: 'You dismantled the physical alarm, synthesized the chromatic wavelengths, and combined the discoveries into the True Key.',
    defaultTrollTitle: 'Override Denied',
    defaultTrollMessage: 'The alarm must be silenced manually, lenses overlapped in pairs, and the 3-letter cipher verified.',
    hint: 'Stage 1: Click wall siren & pull battery. Stage 2: R+G=K, G+B=E, R+B=Y. Stage 3: Set dials to K-E-Y.',
    component: Room18,
  },
  {
    id: 19,
    chapter: 4,
    chapterTitle: 'The Glitched Abyss',
    title: 'Room 19',
    instruction: 'SOLVE 3 STAGES: THE FIRST LAYER, ELZZUP\'S TRAP, & FINAL DEDUCTION.',
    defaultSuccessMessage: 'Singularity Harmonized.',
    defaultSuccessSubmessage: 'You dismantled the inverse loop, bypassed Elzzup\'s traps, and aligned the 6 harmonic vectors.',
    defaultTrollTitle: 'Singularity Collapse',
    defaultTrollMessage: 'Invert sub-core polarity, calibrate wave to Sine, balance 50/50/50 flux, and ignore decoy emergency overrides.',
    hint: 'Stage 1: Invert polarity & balance 50%. Stage 2: Set Sine wave & ignore decoys. Stage 3: Synchronize harmonic singularity.',
    component: Room19,
  },
  {
    id: 20,
    chapter: 4,
    chapterTitle: 'The Glitched Abyss',
    title: 'Room 20',
    instruction: 'CONFRONT ELZZUP ACROSS 5 PHASES: 3 HARD + 2 RAGE-BAIT.',
    defaultSuccessMessage: 'ELZZUP DEFEATED',
    defaultSuccessSubmessage: '...for real.',
    defaultTrollTitle: 'Core Retaliation',
    defaultTrollMessage: 'Shatter shields descending (20.1), filter deceptive core (20.2), balance quantum nodes (20.3), pull data cable (20.4), and decompile root kernel (20.5).',
    hint: '20.1: Gamma->Beta->Alpha. 20.2: Spectrum Lens->Purge Core. 20.3: Both Polarity Inverted & 50 MHz. 20.4: Pull Root Cable. 20.5: Spell P-U-Z-Z-L-E.',
    component: Room20,
  },
];

export function getRoomById(id: number): RoomDefinition | undefined {
  return ROOMS.find((r) => r.id === id);
}

export const TOTAL_ROOMS = 20;
